from tkinter import *
root=Tk()
root.title("application")
root.geometry("500x500")
l1=Label(root,text="Name")
l1.pack()
a1=Entry()
a1.pack()
l2=Label(root,text="Email")
l2.pack()
a2=Entry()
a2.pack()
l3=Label(root,text="Address")
l3.pack()
a3=Entry()
a3.pack()
l4=Label(root,text="City")
l4.pack()
a4=Entry()
a4.pack()
l5=Label(root,text="Pin code")
l5.pack()
a5=Entry()
a5.pack()
l6=Label(root,text="Phone Number")
l6.pack()
a6=Entry()
a6.pack()
b1=Button(root,text="submit" ,bg="black",fg="white")
b1.pack()
root.mainloop()