from tkinter import *
root=Tk()
root.title("ZMKS2110")
root.geometry("500x500")
l1=Label(root,text="login form")
l1.pack()
l1=Label(root,text="USER ID")
l1.pack()
e1=Entry(root)
e1.pack()
l2=Label(root,text="PASSWORD")
l2.pack()
e2=Entry(root)
e2.pack()
b1=Button(root,text="login form",bg="red",fg="blue")
b1.pack()
root.mainloop()